language: android
dist: trusty
android:
  components:
    - tools
    - build-tools-28.0.3
    - android-28
before_install:
  - openssl aes-256-cbc -K $encrypted_24d682c7cdcf_key -iv $encrypted_24d682c7cdcf_iv -in treetracker.keys.properties.enc -out treetracker.keys.properties -d
